; PlatformIO Project Configuration File

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_deps = adafruit/adafruit NeoPixel

build_flags =
    -DUSE_TINYUSB

board_build.arduino.earlephilhower.usb_product = ELRS HID Bridge
board_build.arduino.earlephilhower.usb_manufacturer = Open Source


; -----------------------------------------------------------------------------
; Release build
;
; HID only. No USB CDC debug serial interface.
; -----------------------------------------------------------------------------

[env:pico]
build_flags =
    ${env.build_flags}
    -DELRS_DEBUG=0


; -----------------------------------------------------------------------------
; Debug build
;
; HID + USB CDC serial logging.
; -----------------------------------------------------------------------------

[env:pico_debug]
build_flags =
    ${env.build_flags}
    -DELRS_DEBUG=1