#include "crsf_self_test.h"

#include <stddef.h>
#include <stdint.h>
#include "crsf_decoder.h"
#include "crsf_frame.h"
#include "crsf_parser.h"
#include "crsf_protocol.h"
#include "link_statistics.h"
#include "raw_channels.h"


namespace
{
    // Frozen CRSF 0x16 frame fixture.
    //
    // This fixture is intentionally hard-coded rather than generated by the
    // self-test. That prevents the positive decode test from sharing a runtime
    // packing implementation with the production decoder.
    //
    // Expected channel values:
    //
    //   172, 992, 1811, 500,
    //   1000, 1200, 1500, 700,
    //   0, 2047, 321, 1777,
    //   50, 1024, 1600, 888
    //
    // Frame layout:
    //
    //   Address = 0xC8
    //   Length  = 0x18
    //   Type    = 0x16
    //   Payload = 22 packed channel bytes
    //   CRC     = 0xFD

    constexpr uint8_t GOLDEN_RC_FRAME[] =
    {
        0xC8, 0x18, 0x16,
        0xAC, 0x00, 0xDF, 0xC4, 0xE9, 0x83,
        0x3E, 0x58, 0x72, 0x97, 0x57, 0x00,
        0xF8, 0x7F, 0x50, 0xE2, 0x2D, 0x03,
        0x00, 0x02, 0x19, 0x6F,
        0xFD
    };


    constexpr uint16_t GOLDEN_RC_CHANNELS[16] =
    {
        172,
        992,
        1811,
        500,
        1000,
        1200,
        1500,
        700,
        0,
        2047,
        321,
        1777,
        50,
        1024,
        1600,
        888
    };


    // Frozen CRSF 0x14 Link Statistics frame fixture.
    //
    // Expected payload interpretation:
    //
    //   uplink RSSI antenna 1 = 70
    //   uplink RSSI antenna 2 = 72
    //   uplink link quality   = 99
    //   uplink SNR            = -5
    //   active antenna        = 1
    //   RF profile            = 2
    //   uplink RF power       = 3
    //   downlink RSSI         = 80
    //   downlink link quality = 97
    //   downlink SNR          = -7

    constexpr uint8_t GOLDEN_LINK_STATISTICS_FRAME[] =
    {
        0xC8, 0x0C, 0x14,
        0x46, 0x48, 0x63, 0xFB, 0x01,
        0x02, 0x03, 0x50, 0x61, 0xF9,
        0x68
    };


    bool channelsMatch(
        const RawChannels& decoded,
        const uint16_t* expected
    )
    {
        for (
            uint8_t i = 0;
            i < RawChannels::CHANNEL_COUNT;
            ++i
        )
        {
            if (
                decoded.channel[i] !=
                expected[i]
            )
            {
                return false;
            }
        }

        return true;
    }


    void feedDecoder(
        CrsfDecoder& decoder,
        const uint8_t* bytes,
        size_t byteCount
    )
    {
        for (
            size_t i = 0;
            i < byteCount;
            ++i
        )
        {
            decoder.pushByte(
                bytes[i]
            );
        }
    }


    bool feedParser(
        CrsfParser& parser,
        const uint8_t* bytes,
        size_t byteCount,
        CrsfFrame& parsedFrame
    )
    {
        bool frameReceived = false;

        for (
            size_t i = 0;
            i < byteCount;
            ++i
        )
        {
            if (
                parser.pushByte(
                    bytes[i],
                    parsedFrame
                )
            )
            {
                frameReceived = true;
            }
        }

        return frameReceived;
    }


    void copyBytes(
        const uint8_t* source,
        uint8_t* destination,
        size_t byteCount
    )
    {
        for (
            size_t i = 0;
            i < byteCount;
            ++i
        )
        {
            destination[i] =
                source[i];
        }
    }


    bool runGoldenRcFrameTest()
    {
        CrsfDecoder decoder;

        feedDecoder(
            decoder,
            GOLDEN_RC_FRAME,
            sizeof(GOLDEN_RC_FRAME)
        );

        if (!decoder.hasNewChannels())
        {
            return false;
        }

        return channelsMatch(
            decoder.getChannels(),
            GOLDEN_RC_CHANNELS
        );
    }


    bool runGoldenLinkStatisticsTest()
    {
        CrsfDecoder decoder;

        feedDecoder(
            decoder,
            GOLDEN_LINK_STATISTICS_FRAME,
            sizeof(GOLDEN_LINK_STATISTICS_FRAME)
        );

        if (!decoder.hasNewLinkStatistics())
        {
            return false;
        }

        const LinkStatistics& statistics =
            decoder.getLinkStatistics();

        return
            statistics.uplinkRssiAntenna1 == 70 &&
            statistics.uplinkRssiAntenna2 == 72 &&
            statistics.uplinkLinkQuality == 99 &&
            statistics.uplinkSnr == -5 &&
            statistics.activeAntenna == 1 &&
            statistics.rfProfile == 2 &&
            statistics.uplinkRfPower == 3 &&
            statistics.downlinkRssi == 80 &&
            statistics.downlinkLinkQuality == 97 &&
            statistics.downlinkSnr == -7;
    }


    bool runBadCrcTest()
    {
        uint8_t frame[sizeof(GOLDEN_RC_FRAME)] = {};

        copyBytes(
            GOLDEN_RC_FRAME,
            frame,
            sizeof(frame)
        );

        // Deliberately corrupt the CRC of the frozen fixture.
        frame[sizeof(frame) - 1] ^= 0xFF;

        CrsfDecoder decoder;

        feedDecoder(
            decoder,
            frame,
            sizeof(frame)
        );

        // A corrupted frame must never publish channels.
        return !decoder.hasNewChannels();
    }


    bool runValidSyncAddressTest()
    {
        // Representative valid CRSF frame-start values.
        //
        // These cover:
        //
        // - traditional serial sync / Flight Controller
        // - broadcast
        // - Remote Control
        // - Receiver
        // - Transmitter Module
        // - dynamic/NAT address space
        constexpr uint8_t validAddresses[] =
        {
            Crsf::ADDRESS_FLIGHT_CONTROLLER,
            Crsf::ADDRESS_BROADCAST,
            Crsf::ADDRESS_REMOTE_CONTROL,
            Crsf::ADDRESS_RECEIVER,
            Crsf::ADDRESS_TRANSMITTER,
            Crsf::ADDRESS_DYNAMIC_MIN
        };

        for (
            size_t addressIndex = 0;
            addressIndex <
                sizeof(validAddresses) /
                sizeof(validAddresses[0]);
            ++addressIndex
        )
        {
            uint8_t frameBytes[sizeof(GOLDEN_RC_FRAME)] = {};

            copyBytes(
                GOLDEN_RC_FRAME,
                frameBytes,
                sizeof(frameBytes)
            );

            // CRSF CRC excludes the address and length bytes, so the frozen
            // frame remains CRC-valid when only the sync/address byte changes.
            frameBytes[0] =
                validAddresses[addressIndex];

            CrsfParser parser;
            CrsfFrame parsedFrame;

            if (
                !feedParser(
                    parser,
                    frameBytes,
                    sizeof(frameBytes),
                    parsedFrame
                )
            )
            {
                return false;
            }

            if (
                parsedFrame.address !=
                validAddresses[addressIndex]
            )
            {
                return false;
            }

            if (
                parsedFrame.type !=
                Crsf::FRAME_RC_CHANNELS
            )
            {
                return false;
            }

            if (
                parsedFrame.payloadLength !=
                Crsf::RC_CHANNEL_PAYLOAD_SIZE
            )
            {
                return false;
            }
        }

        return true;
    }


    bool runInvalidSyncRecoveryTest()
    {
        CrsfParser parser;
        CrsfFrame parsedFrame;

        // 0x01 is not currently assigned as a CRSF device address and is
        // outside the defined dynamic-address range. It must be ignored as a
        // frame start without preventing the following valid frame from being
        // received.
        if (
            parser.pushByte(
                0x01,
                parsedFrame
            )
        )
        {
            return false;
        }

        if (
            !feedParser(
                parser,
                GOLDEN_RC_FRAME,
                sizeof(GOLDEN_RC_FRAME),
                parsedFrame
            )
        )
        {
            return false;
        }

        return
            parsedFrame.address ==
                Crsf::ADDRESS_FLIGHT_CONTROLLER &&
            parsedFrame.type ==
                Crsf::FRAME_RC_CHANNELS;
    }


    bool runGoodGarbageGoodRecoveryTest()
    {
        CrsfDecoder decoder;

        // Establish a known-good starting point.
        feedDecoder(
            decoder,
            GOLDEN_RC_FRAME,
            sizeof(GOLDEN_RC_FRAME)
        );

        if (!decoder.hasNewChannels())
        {
            return false;
        }

        if (
            !channelsMatch(
                decoder.getChannels(),
                GOLDEN_RC_CHANNELS
            )
        )
        {
            return false;
        }

        decoder.clearNewChannels();

        // Mix ordinary garbage with valid CRSF sync/address values followed
        // by impossible length bytes. The parser must reject each candidate
        // and return to synchronization search.
        constexpr uint8_t garbage[] =
        {
            0x55,
            0xAA,
            Crsf::ADDRESS_RECEIVER,
            0x01,
            0x7E,
            Crsf::ADDRESS_TRANSMITTER,
            0xFF,
            0x11
        };

        feedDecoder(
            decoder,
            garbage,
            sizeof(garbage)
        );

        if (decoder.hasNewChannels())
        {
            return false;
        }

        // The next valid frame must still decode normally.
        feedDecoder(
            decoder,
            GOLDEN_RC_FRAME,
            sizeof(GOLDEN_RC_FRAME)
        );

        if (!decoder.hasNewChannels())
        {
            return false;
        }

        return channelsMatch(
            decoder.getChannels(),
            GOLDEN_RC_CHANNELS
        );
    }


    bool runBadFrameThenGoodRecoveryTest()
    {
        uint8_t badFrame[sizeof(GOLDEN_RC_FRAME)] = {};

        copyBytes(
            GOLDEN_RC_FRAME,
            badFrame,
            sizeof(badFrame)
        );

        badFrame[sizeof(badFrame) - 1] ^= 0x01;

        CrsfDecoder decoder;

        feedDecoder(
            decoder,
            badFrame,
            sizeof(badFrame)
        );

        if (decoder.hasNewChannels())
        {
            return false;
        }

        feedDecoder(
            decoder,
            GOLDEN_RC_FRAME,
            sizeof(GOLDEN_RC_FRAME)
        );

        if (!decoder.hasNewChannels())
        {
            return false;
        }

        return channelsMatch(
            decoder.getChannels(),
            GOLDEN_RC_CHANNELS
        );
    }


    bool runRepeatedResynchronizationTest()
    {
        CrsfParser parser;
        CrsfFrame parsedFrame;

        // Exercise repeated invalid-length recovery. Several bytes that fail
        // as a length are themselves valid CRSF sync/address bytes, forcing
        // the parser to preserve them as the start of the next candidate.
        constexpr uint8_t resyncSequence[] =
        {
            Crsf::ADDRESS_FLIGHT_CONTROLLER,
            0x01,

            Crsf::ADDRESS_REMOTE_CONTROL,
            0x3F,

            Crsf::ADDRESS_RECEIVER,
            0x00,

            0xFF
        };

        if (
            feedParser(
                parser,
                resyncSequence,
                sizeof(resyncSequence),
                parsedFrame
            )
        )
        {
            return false;
        }

        if (
            !feedParser(
                parser,
                GOLDEN_RC_FRAME,
                sizeof(GOLDEN_RC_FRAME),
                parsedFrame
            )
        )
        {
            return false;
        }

        return
            parsedFrame.address ==
                Crsf::ADDRESS_FLIGHT_CONTROLLER &&
            parsedFrame.type ==
                Crsf::FRAME_RC_CHANNELS &&
            parsedFrame.payloadLength ==
                Crsf::RC_CHANNEL_PAYLOAD_SIZE;
    }
}


bool CrsfSelfTest::run()
{
    if (!runGoldenRcFrameTest())
    {
        return false;
    }

    if (!runGoldenLinkStatisticsTest())
    {
        return false;
    }

    if (!runBadCrcTest())
    {
        return false;
    }

    if (!runValidSyncAddressTest())
    {
        return false;
    }

    if (!runInvalidSyncRecoveryTest())
    {
        return false;
    }

    if (!runGoodGarbageGoodRecoveryTest())
    {
        return false;
    }

    if (!runBadFrameThenGoodRecoveryTest())
    {
        return false;
    }

    if (!runRepeatedResynchronizationTest())
    {
        return false;
    }

    return true;
}
